# Generates include/build_info.h with FW_VERSION_STR, BUILD_DATE_STR and
# UI_VERSION_STR on each build.
#
# FW_VERSION_STR is `git describe` against v* release tags — the single source
# of truth for the firmware version. Exact tag -> "v1.2.3"; commits past a tag
# -> "v1.2.3-4-gabc123"; no tag / no git -> "v0.0.0-dev[+sha]".
# BUILD_DATE_STR is today's date (YYYY-MM-DD).
# UI_VERSION_STR is the modification date of the EEZ project file
# (../UI/Helgatchi UI.eez-project) — bumps whenever the UI is re-saved.
#
# The file is only rewritten when its content actually changes, so daily
# builds don't gratuitously trigger a recompile of whatever includes
# version.h.

import os
import datetime
import subprocess

Import("env")  # noqa: F821

PROJECT_DIR = env["PROJECT_DIR"]
OUT_PATH    = os.path.join(PROJECT_DIR, "include", "build_info.h")
EEZ_PATH    = os.path.normpath(
    os.path.join(PROJECT_DIR, "..", "UI", "Helgatchi UI.eez-project")
)


def git_describe():
    """Return `git describe` for v* tags, or None if unavailable."""
    try:
        out = subprocess.check_output(
            ["git", "describe", "--tags", "--always", "--dirty", "--match", "v*"],
            cwd=PROJECT_DIR, stderr=subprocess.DEVNULL,
        ).decode("utf-8", "replace").strip()
        return out or None
    except (OSError, subprocess.CalledProcessError):
        return None


_desc = git_describe()
if not _desc:
    fw_version = "v0.0.0-dev"
elif not _desc.startswith("v"):
    # --always fell back to a bare commit sha: no v* tag exists yet.
    fw_version = f"v0.0.0-dev+{_desc}"
else:
    fw_version = _desc

build_date = datetime.date.today().isoformat()

ui_version = "unknown"
if os.path.isfile(EEZ_PATH):
    ui_version = datetime.date.fromtimestamp(os.path.getmtime(EEZ_PATH)).isoformat()

contents = (
    "#pragma once\n"
    "// Auto-generated by scripts/build_info.py — do not edit by hand.\n"
    f"#define FW_VERSION_STR \"{fw_version}\"\n"
    f"#define BUILD_DATE_STR \"{build_date}\"\n"
    f"#define UI_VERSION_STR \"{ui_version}\"\n"
)

existing = ""
if os.path.isfile(OUT_PATH):
    try:
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            existing = f.read()
    except OSError:
        pass

if existing != contents:
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(contents)
    print(f"[build_info] regenerated: fw={fw_version} build={build_date} ui={ui_version}")
else:
    print(f"[build_info] up to date: fw={fw_version} build={build_date} ui={ui_version}")
