# Generates include/build_info.h with BUILD_DATE_STR and UI_VERSION_STR
# on each build.
#
# BUILD_DATE_STR is today's date (YYYY-MM-DD).
# UI_VERSION_STR is the modification date of the EEZ project file
# (../UI/Helgatchi UI.eez-project) — bumps whenever the UI is re-saved.
#
# The file is only rewritten when its content actually changes, so daily
# builds don't gratuitously trigger a recompile of whatever includes
# version.h.

import os
import datetime

Import("env")  # noqa: F821

PROJECT_DIR = env["PROJECT_DIR"]
OUT_PATH    = os.path.join(PROJECT_DIR, "include", "build_info.h")
EEZ_PATH    = os.path.normpath(
    os.path.join(PROJECT_DIR, "..", "UI", "Helgatchi UI.eez-project")
)

build_date = datetime.date.today().isoformat()

ui_version = "unknown"
if os.path.isfile(EEZ_PATH):
    ui_version = datetime.date.fromtimestamp(os.path.getmtime(EEZ_PATH)).isoformat()

contents = (
    "#pragma once\n"
    "// Auto-generated by scripts/build_info.py — do not edit by hand.\n"
    f"#define BUILD_DATE_STR \"{build_date}\"\n"
    f"#define UI_VERSION_STR \"{ui_version}\"\n"
)

existing = ""
if os.path.isfile(OUT_PATH):
    try:
        with open(OUT_PATH, "r", encoding="utf-8") as f:
            existing = f.read()
    except OSError:
        pass

if existing != contents:
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(contents)
    print(f"[build_info] regenerated: build={build_date} ui={ui_version}")
else:
    print(f"[build_info] up to date: build={build_date} ui={ui_version}")
