#include "images.h"

const ext_img_desc_t images[49] = {
    { "DC801 Logo", &img_dc801_logo },
    { "helga_sit_scoot1", &img_helga_sit_scoot1 },
    { "helga_sit_scoot2", &img_helga_sit_scoot2 },
    { "helga_walk1", &img_helga_walk1 },
    { "helga_walk2", &img_helga_walk2 },
    { "helga_walk3", &img_helga_walk3 },
    { "helga_walk4", &img_helga_walk4 },
    { "helga_dance_party1", &img_helga_dance_party1 },
    { "helga_dance_party2", &img_helga_dance_party2 },
    { "helga_dance_party3", &img_helga_dance_party3 },
    { "helga_dance_party4", &img_helga_dance_party4 },
    { "helga_dance_party5", &img_helga_dance_party5 },
    { "helga_dance_party6", &img_helga_dance_party6 },
    { "helga_dance_party7", &img_helga_dance_party7 },
    { "helga_dance_party8", &img_helga_dance_party8 },
    { "helga_dance1", &img_helga_dance1 },
    { "helga_dance2", &img_helga_dance2 },
    { "helga_dance3", &img_helga_dance3 },
    { "helga_dance4", &img_helga_dance4 },
    { "helga_dance5", &img_helga_dance5 },
    { "helga_dance6", &img_helga_dance6 },
    { "helga_dance7", &img_helga_dance7 },
    { "helga_dance8", &img_helga_dance8 },
    { "helga_sniff_alert1", &img_helga_sniff_alert1 },
    { "helga_sniff_alert2", &img_helga_sniff_alert2 },
    { "helga_sniff_alert3", &img_helga_sniff_alert3 },
    { "helga_sniff_alert4", &img_helga_sniff_alert4 },
    { "helga_sniff_end1", &img_helga_sniff_end1 },
    { "helga_sniff_end2", &img_helga_sniff_end2 },
    { "helga_sniff_end3", &img_helga_sniff_end3 },
    { "helga_sniff_loop1", &img_helga_sniff_loop1 },
    { "helga_sniff_loop2", &img_helga_sniff_loop2 },
    { "helga_sniff_loop3", &img_helga_sniff_loop3 },
    { "helga_sniff_loop4", &img_helga_sniff_loop4 },
    { "helga_sniff_start1", &img_helga_sniff_start1 },
    { "helga_sniff_start2", &img_helga_sniff_start2 },
    { "helga_brush1", &img_helga_brush1 },
    { "helga_brush2", &img_helga_brush2 },
    { "helga_brush3", &img_helga_brush3 },
    { "helga_brush4", &img_helga_brush4 },
    { "helga_brush5", &img_helga_brush5 },
    { "helga_idle1", &img_helga_idle1 },
    { "helga_idle2", &img_helga_idle2 },
    { "helga_idle3", &img_helga_idle3 },
    { "helga_idle4", &img_helga_idle4 },
    { "helga_idle5", &img_helga_idle5 },
    { "helga_idle6", &img_helga_idle6 },
    { "helga_idle7", &img_helga_idle7 },
    { "helga_idle8", &img_helga_idle8 },
};