// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef _UI_COMP_TOP_BAR_RIGHT_TEXT_H
#define _UI_COMP_TOP_BAR_RIGHT_TEXT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Top Bar Right Text
#define UI_COMP_TOP_BAR_RIGHT_TEXT_LABEL_TOP_BAR_RIGHT_TEXT 0
#define _UI_COMP_TOP_BAR_RIGHT_TEXT_NUM 1
lv_obj_t * ui_label_top_bar_right_text_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
