// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

void ui_comp_Label_Top_Bar_Center_Text_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Label_Top_Bar_Left_Text_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Label_Top_Bar_Right_Text_create_hook(lv_obj_t * comp)
{
}

void ui_comp_label_top_bar_center_text_create_hook(lv_obj_t * comp)
{
}

void ui_comp_label_top_bar_left_text_create_hook(lv_obj_t * comp)
{
}

void ui_comp_label_top_bar_right_text_create_hook(lv_obj_t * comp)
{
}
