// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

// COMPONENT Top Bar Right Text

lv_obj_t * ui_label_top_bar_right_text_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_label_top_bar_right_text;
    cui_label_top_bar_right_text = lv_label_create(comp_parent);
    lv_obj_set_width(cui_label_top_bar_right_text, lv_pct(25));
    lv_obj_set_height(cui_label_top_bar_right_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_label_top_bar_right_text, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(cui_label_top_bar_right_text, "??%");
    lv_obj_set_style_text_align(cui_label_top_bar_right_text, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_label_top_bar_right_text, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TOP_BAR_RIGHT_TEXT_NUM);
    children[UI_COMP_TOP_BAR_RIGHT_TEXT_LABEL_TOP_BAR_RIGHT_TEXT] = cui_label_top_bar_right_text;
    lv_obj_add_event_cb(cui_label_top_bar_right_text, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_label_top_bar_right_text, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_label_top_bar_right_text_create_hook(cui_label_top_bar_right_text);
    return cui_label_top_bar_right_text;
}

