// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef _HELGATCHI_UI_UI_COMP_HOOK_H
#define _HELGATCHI_UI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_label_top_bar_center_text_create_hook(lv_obj_t * comp);
void ui_comp_label_top_bar_right_text_create_hook(lv_obj_t * comp);
void ui_comp_label_top_bar_left_text_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
