// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

lv_obj_t * uic_Status_Screen_Panel_Top_Bar;
lv_obj_t * uic_Status_Screen_Container_Main_Container;
lv_obj_t * uic_Screen_Status_Screen;
lv_obj_t * ui_screen_status_screen = NULL;
lv_obj_t * ui_status_screen_container_main_container = NULL;
lv_obj_t * ui_status_screen_panel_top_bar = NULL;
lv_obj_t * ui_status_screen_top_bar_left_text_top_bar_left_text1 = NULL;
lv_obj_t * ui_status_screen_top_bar_center_text_centertext = NULL;
lv_obj_t * ui_status_screen_top_bar_right_text_righttext = NULL;
lv_obj_t * ui_status_screen_panel_panel3 = NULL;
lv_obj_t * ui_status_screen_label_label8 = NULL;
lv_obj_t * ui_status_screen_label_label9 = NULL;
// event funtions

// build funtions

void ui_screen_status_screen_screen_init(void)
{
    ui_screen_status_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_status_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_screen_container_main_container = lv_obj_create(ui_screen_status_screen);
    lv_obj_remove_style_all(ui_status_screen_container_main_container);
    lv_obj_set_width(ui_status_screen_container_main_container, lv_pct(95));
    lv_obj_set_height(ui_status_screen_container_main_container, lv_pct(95));
    lv_obj_set_align(ui_status_screen_container_main_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_status_screen_container_main_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_status_screen_container_main_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_status_screen_container_main_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_status_screen_container_main_container, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_status_screen_panel_top_bar = lv_obj_create(ui_status_screen_container_main_container);
    lv_obj_set_width(ui_status_screen_panel_top_bar, lv_pct(100));
    lv_obj_set_height(ui_status_screen_panel_top_bar, lv_pct(15));
    lv_obj_set_align(ui_status_screen_panel_top_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_status_screen_panel_top_bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_screen_top_bar_left_text_top_bar_left_text1 = ui_label_top_bar_left_text_create(
                                                                ui_status_screen_panel_top_bar);
    lv_obj_set_x(ui_status_screen_top_bar_left_text_top_bar_left_text1, 0);
    lv_obj_set_y(ui_status_screen_top_bar_left_text_top_bar_left_text1, 0);
    lv_label_set_text(ui_status_screen_top_bar_left_text_top_bar_left_text1, "zzz");

    ui_status_screen_top_bar_center_text_centertext = ui_label_top_bar_center_text_create(ui_status_screen_panel_top_bar);
    lv_obj_set_x(ui_status_screen_top_bar_center_text_centertext, 0);
    lv_obj_set_y(ui_status_screen_top_bar_center_text_centertext, 0);
    lv_label_set_text(ui_status_screen_top_bar_center_text_centertext, "Status");

    ui_status_screen_top_bar_right_text_righttext = ui_label_top_bar_right_text_create(ui_status_screen_panel_top_bar);
    lv_obj_set_x(ui_status_screen_top_bar_right_text_righttext, 0);
    lv_obj_set_y(ui_status_screen_top_bar_right_text_righttext, 0);

    ui_status_screen_panel_panel3 = lv_obj_create(ui_status_screen_container_main_container);
    lv_obj_set_width(ui_status_screen_panel_panel3, lv_pct(100));
    lv_obj_set_height(ui_status_screen_panel_panel3, lv_pct(70));
    lv_obj_set_align(ui_status_screen_panel_panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_status_screen_panel_panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_status_screen_panel_panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_status_screen_panel_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_screen_label_label8 = lv_label_create(ui_status_screen_panel_panel3);
    lv_obj_set_width(ui_status_screen_label_label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status_screen_label_label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_status_screen_label_label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status_screen_label_label8, "Quick-look device info");

    ui_status_screen_label_label9 = lv_label_create(ui_status_screen_panel_panel3);
    lv_obj_set_width(ui_status_screen_label_label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_status_screen_label_label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_status_screen_label_label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status_screen_label_label9, "Scannning: BT\nMode: Power-Saver\nScan: in 12s for 5s\n");
    lv_obj_set_style_text_font(ui_status_screen_label_label9, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Screen_Status_Screen = ui_screen_status_screen;
    uic_Status_Screen_Container_Main_Container = ui_status_screen_container_main_container;
    uic_Status_Screen_Panel_Top_Bar = ui_status_screen_panel_top_bar;

}

void ui_screen_status_screen_screen_destroy(void)
{
    if(ui_screen_status_screen) lv_obj_del(ui_screen_status_screen);

    // NULL screen variables
    uic_Screen_Status_Screen = NULL;
    ui_screen_status_screen = NULL;
    uic_Status_Screen_Container_Main_Container = NULL;
    ui_status_screen_container_main_container = NULL;
    uic_Status_Screen_Panel_Top_Bar = NULL;
    ui_status_screen_panel_top_bar = NULL;
    ui_status_screen_top_bar_left_text_top_bar_left_text1 = NULL;
    ui_status_screen_top_bar_center_text_centertext = NULL;
    ui_status_screen_top_bar_right_text_righttext = NULL;
    ui_status_screen_panel_panel3 = NULL;
    ui_status_screen_label_label8 = NULL;
    ui_status_screen_label_label9 = NULL;

}
