// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

lv_obj_t * uic_Settings_Screen_Button_Shipping_mode;
lv_obj_t * uic_Settings_Screen_Label_button_text;
lv_obj_t * uic_Settings_Screen_Button_reboot;
lv_obj_t * uic_Settings_Screen_Label_sleep_button_text;
lv_obj_t * uic_Settings_Screen_Button_sleep;
lv_obj_t * uic_Settings_Screen_Switch_Sleep_while_USB;
lv_obj_t * uic_Settings_Screen_Switch_Sleep_while_Serial;
lv_obj_t * uic_Settings_Screen_Label_Sleep_while_serial_text;
lv_obj_t * uic_Settings_Screen_Dropdown_Debug_level;
lv_obj_t * uic_Settings_Screen_Label_Debug_Level_Text;
lv_obj_t * uic_Settings_Screen_Switch_Debug_over_Serial;
lv_obj_t * uic_Settings_Screen_Label_Debug_over_Serial_text;
lv_obj_t * uic_Settings_Screen_Container_Option_1;
lv_obj_t * uic_Settings_Screen_Dropdown_performance_mode;
lv_obj_t * uic_Settings_Screen_Label_Scan_mode_text;
lv_obj_t * uic_Settings_Screen_Switch_Wifi_scanning;
lv_obj_t * uic_Settings_Screen_Label_Wifi_Scanning_text;
lv_obj_t * uic_Settings_Screen_Switch_BLE_Scanning;
lv_obj_t * uic_Settings_Screen_Label_BLE_Scanning_text;
lv_obj_t * uic_Settings_Screen_Label_Scanning_mode_section;
lv_obj_t * uic_Settings_Screen_Dropdown_Brightness;
lv_obj_t * uic_Settings_Screen_Label_Screen_Brightness_text;
lv_obj_t * uic_Settings_Screen_Label_Screen_and_brightness_section;
lv_obj_t * uic_Settings_Screen_Panel_Panel2;
lv_obj_t * uic_Settings_Screen_Container_Main_Container;
lv_obj_t * uic_Screen_Settings_Screen;
lv_obj_t * ui_screen_settings_screen = NULL;
lv_obj_t * ui_settings_screen_container_main_container = NULL;
lv_obj_t * ui_settings_screen_panel_top_bar2 = NULL;
lv_obj_t * ui_settings_screen_top_bar_left_text_top_bar_left_text3 = NULL;
lv_obj_t * ui_settings_screen_top_bar_center_text_centertext2 = NULL;
lv_obj_t * ui_settings_screen_top_bar_right_text_righttext2 = NULL;
lv_obj_t * ui_settings_screen_panel_panel2 = NULL;
lv_obj_t * ui_settings_screen_label_screen_and_brightness_section = NULL;
lv_obj_t * ui_settings_screen_container_option_4 = NULL;
lv_obj_t * ui_settings_screen_label_screen_brightness_text = NULL;
lv_obj_t * ui_settings_screen_dropdown_brightness = NULL;
lv_obj_t * ui_settings_screen_label_scanning_mode_section = NULL;
lv_obj_t * ui_settings_screen_container_option_5 = NULL;
lv_obj_t * ui_settings_screen_label_ble_scanning_text = NULL;
lv_obj_t * ui_settings_screen_switch_ble_scanning = NULL;
lv_obj_t * ui_settings_screen_container_option_6 = NULL;
lv_obj_t * ui_settings_screen_label_wifi_scanning_text = NULL;
lv_obj_t * ui_settings_screen_switch_wifi_scanning = NULL;
lv_obj_t * ui_settings_screen_container_option_7 = NULL;
lv_obj_t * ui_settings_screen_label_scan_mode_text = NULL;
lv_obj_t * ui_settings_screen_dropdown_performance_mode = NULL;
lv_obj_t * ui_settings_screen_label_debug_section = NULL;
lv_obj_t * ui_settings_screen_container_option_1 = NULL;
lv_obj_t * ui_settings_screen_label_debug_over_serial_text = NULL;
lv_obj_t * ui_settings_screen_switch_debug_over_serial = NULL;
lv_obj_t * ui_settings_screen_container_option_2 = NULL;
lv_obj_t * ui_settings_screen_label_debug_level_text = NULL;
lv_obj_t * ui_settings_screen_dropdown_debug_level = NULL;
lv_obj_t * ui_settings_screen_container_option_3 = NULL;
lv_obj_t * ui_settings_screen_label_sleep_while_serial_text = NULL;
lv_obj_t * ui_settings_screen_switch_sleep_while_serial = NULL;
lv_obj_t * ui_settings_screen_container_option_11 = NULL;
lv_obj_t * ui_settings_screen_label_sleep_while_usb_text = NULL;
lv_obj_t * ui_settings_screen_switch_sleep_while_usb = NULL;
lv_obj_t * ui_settings_screen_container_option_10 = NULL;
lv_obj_t * ui_settings_screen_label_sleep_text = NULL;
lv_obj_t * ui_settings_screen_button_sleep = NULL;
lv_obj_t * ui_settings_screen_label_sleep_button_text = NULL;
lv_obj_t * ui_settings_screen_container_option_8 = NULL;
lv_obj_t * ui_settings_screen_label_reboot_text1 = NULL;
lv_obj_t * ui_settings_screen_button_reboot = NULL;
lv_obj_t * ui_settings_screen_label_reboot_button_text = NULL;
lv_obj_t * ui_settings_screen_container_option_9 = NULL;
lv_obj_t * ui_settings_screen_label_shipping_mode_test = NULL;
lv_obj_t * ui_settings_screen_button_shipping_mode = NULL;
lv_obj_t * ui_settings_screen_label_shipping_mode_button_text = NULL;
// event funtions

// build funtions

void ui_screen_settings_screen_screen_init(void)
{
    ui_screen_settings_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_settings_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_container_main_container = lv_obj_create(ui_screen_settings_screen);
    lv_obj_remove_style_all(ui_settings_screen_container_main_container);
    lv_obj_set_width(ui_settings_screen_container_main_container, lv_pct(95));
    lv_obj_set_height(ui_settings_screen_container_main_container, lv_pct(95));
    lv_obj_set_align(ui_settings_screen_container_main_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_settings_screen_container_main_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settings_screen_container_main_container, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_main_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_settings_screen_container_main_container, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_panel_top_bar2 = lv_obj_create(ui_settings_screen_container_main_container);
    lv_obj_set_width(ui_settings_screen_panel_top_bar2, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_panel_top_bar2, lv_pct(15));
    lv_obj_set_align(ui_settings_screen_panel_top_bar2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_settings_screen_panel_top_bar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_top_bar_left_text_top_bar_left_text3 = ui_label_top_bar_left_text_create(
                                                                  ui_settings_screen_panel_top_bar2);
    lv_obj_set_x(ui_settings_screen_top_bar_left_text_top_bar_left_text3, 0);
    lv_obj_set_y(ui_settings_screen_top_bar_left_text_top_bar_left_text3, 0);
    lv_label_set_text(ui_settings_screen_top_bar_left_text_top_bar_left_text3, "zzz");

    ui_settings_screen_top_bar_center_text_centertext2 = ui_label_top_bar_center_text_create(
                                                             ui_settings_screen_panel_top_bar2);
    lv_obj_set_x(ui_settings_screen_top_bar_center_text_centertext2, 0);
    lv_obj_set_y(ui_settings_screen_top_bar_center_text_centertext2, 0);
    lv_label_set_text(ui_settings_screen_top_bar_center_text_centertext2, "Settings");

    ui_settings_screen_top_bar_right_text_righttext2 = ui_label_top_bar_right_text_create(
                                                           ui_settings_screen_panel_top_bar2);
    lv_obj_set_x(ui_settings_screen_top_bar_right_text_righttext2, 0);
    lv_obj_set_y(ui_settings_screen_top_bar_right_text_righttext2, 0);

    ui_settings_screen_panel_panel2 = lv_obj_create(ui_settings_screen_container_main_container);
    lv_obj_set_width(ui_settings_screen_panel_panel2, lv_pct(100));
    lv_obj_set_flex_grow(ui_settings_screen_panel_panel2, 1);
    lv_obj_set_align(ui_settings_screen_panel_panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_settings_screen_panel_panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settings_screen_panel_panel2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_settings_screen_panel_panel2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_settings_screen_panel_panel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_screen_panel_panel2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_label_screen_and_brightness_section = lv_label_create(ui_settings_screen_panel_panel2);
    lv_obj_set_width(ui_settings_screen_label_screen_and_brightness_section, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_screen_and_brightness_section, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_screen_and_brightness_section, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_screen_and_brightness_section, "Brightness");
    lv_obj_set_style_text_decor(ui_settings_screen_label_screen_and_brightness_section, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_container_option_4 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_4);
    lv_obj_set_width(ui_settings_screen_container_option_4, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_settings_screen_container_option_4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_4,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_screen_brightness_text = lv_label_create(ui_settings_screen_container_option_4);
    lv_obj_set_width(ui_settings_screen_label_screen_brightness_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_screen_brightness_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_screen_brightness_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_screen_brightness_text, "Screen");

    ui_settings_screen_dropdown_brightness = lv_dropdown_create(ui_settings_screen_container_option_4);
    lv_dropdown_set_options(ui_settings_screen_dropdown_brightness, "Min\nLow\nMedium\nHigh\nMax");
    lv_obj_set_width(ui_settings_screen_dropdown_brightness, lv_pct(55));
    lv_obj_set_height(ui_settings_screen_dropdown_brightness, lv_pct(100));
    lv_obj_set_align(ui_settings_screen_dropdown_brightness, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_dropdown_brightness, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_settings_screen_label_scanning_mode_section = lv_label_create(ui_settings_screen_panel_panel2);
    lv_obj_set_width(ui_settings_screen_label_scanning_mode_section, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_scanning_mode_section, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_scanning_mode_section, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_scanning_mode_section, "Scaning & Performance");
    lv_obj_set_style_text_decor(ui_settings_screen_label_scanning_mode_section, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_container_option_5 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_5);
    lv_obj_set_width(ui_settings_screen_container_option_5, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_5, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_5,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_ble_scanning_text = lv_label_create(ui_settings_screen_container_option_5);
    lv_obj_set_width(ui_settings_screen_label_ble_scanning_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_ble_scanning_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_ble_scanning_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_ble_scanning_text, "BLE Scanning");

    ui_settings_screen_switch_ble_scanning = lv_switch_create(ui_settings_screen_container_option_5);
    lv_obj_set_width(ui_settings_screen_switch_ble_scanning, 50);
    lv_obj_set_height(ui_settings_screen_switch_ble_scanning, 20);
    lv_obj_set_align(ui_settings_screen_switch_ble_scanning, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_border_color(ui_settings_screen_switch_ble_scanning, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_settings_screen_switch_ble_scanning, 255, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_settings_screen_container_option_6 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_6);
    lv_obj_set_width(ui_settings_screen_container_option_6, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_6, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_6,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_wifi_scanning_text = lv_label_create(ui_settings_screen_container_option_6);
    lv_obj_set_width(ui_settings_screen_label_wifi_scanning_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_wifi_scanning_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_wifi_scanning_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_wifi_scanning_text, "WiFi Scanning");

    ui_settings_screen_switch_wifi_scanning = lv_switch_create(ui_settings_screen_container_option_6);
    lv_obj_set_width(ui_settings_screen_switch_wifi_scanning, 50);
    lv_obj_set_height(ui_settings_screen_switch_wifi_scanning, 20);
    lv_obj_set_align(ui_settings_screen_switch_wifi_scanning, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_border_color(ui_settings_screen_switch_wifi_scanning, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_settings_screen_switch_wifi_scanning, 255, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_settings_screen_container_option_7 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_7);
    lv_obj_set_width(ui_settings_screen_container_option_7, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_7, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_7,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_scan_mode_text = lv_label_create(ui_settings_screen_container_option_7);
    lv_obj_set_width(ui_settings_screen_label_scan_mode_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_scan_mode_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_scan_mode_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_scan_mode_text, "Scan Mode");

    ui_settings_screen_dropdown_performance_mode = lv_dropdown_create(ui_settings_screen_container_option_7);
    lv_dropdown_set_options(ui_settings_screen_dropdown_performance_mode, "Performance\nBalanced\nPower Saver");
    lv_obj_set_width(ui_settings_screen_dropdown_performance_mode, lv_pct(60));
    lv_obj_set_height(ui_settings_screen_dropdown_performance_mode, lv_pct(100));
    lv_obj_set_align(ui_settings_screen_dropdown_performance_mode, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_dropdown_performance_mode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_settings_screen_label_debug_section = lv_label_create(ui_settings_screen_panel_panel2);
    lv_obj_set_width(ui_settings_screen_label_debug_section, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_debug_section, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_debug_section, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_debug_section, "Debug Options");
    lv_obj_set_style_text_decor(ui_settings_screen_label_debug_section, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_screen_container_option_1 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_1);
    lv_obj_set_width(ui_settings_screen_container_option_1, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_debug_over_serial_text = lv_label_create(ui_settings_screen_container_option_1);
    lv_obj_set_width(ui_settings_screen_label_debug_over_serial_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_debug_over_serial_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_debug_over_serial_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_debug_over_serial_text, "Debug over Serial");

    ui_settings_screen_switch_debug_over_serial = lv_switch_create(ui_settings_screen_container_option_1);
    lv_obj_set_width(ui_settings_screen_switch_debug_over_serial, 50);
    lv_obj_set_height(ui_settings_screen_switch_debug_over_serial, 20);
    lv_obj_set_align(ui_settings_screen_switch_debug_over_serial, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_border_color(ui_settings_screen_switch_debug_over_serial, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_settings_screen_switch_debug_over_serial, 255, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_settings_screen_container_option_2 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_2);
    lv_obj_set_width(ui_settings_screen_container_option_2, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_debug_level_text = lv_label_create(ui_settings_screen_container_option_2);
    lv_obj_set_width(ui_settings_screen_label_debug_level_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_debug_level_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_debug_level_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_debug_level_text, "Debug level");

    ui_settings_screen_dropdown_debug_level = lv_dropdown_create(ui_settings_screen_container_option_2);
    lv_dropdown_set_options(ui_settings_screen_dropdown_debug_level, "Info\nHigh\nRender\nScan");
    lv_obj_set_height(ui_settings_screen_dropdown_debug_level, 20);
    lv_obj_set_width(ui_settings_screen_dropdown_debug_level, lv_pct(55));
    lv_obj_set_align(ui_settings_screen_dropdown_debug_level, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_dropdown_debug_level, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_settings_screen_container_option_3 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_3);
    lv_obj_set_width(ui_settings_screen_container_option_3, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_3, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_sleep_while_serial_text = lv_label_create(ui_settings_screen_container_option_3);
    lv_obj_set_width(ui_settings_screen_label_sleep_while_serial_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_sleep_while_serial_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_sleep_while_serial_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_sleep_while_serial_text, "Sleep with Serial");

    ui_settings_screen_switch_sleep_while_serial = lv_switch_create(ui_settings_screen_container_option_3);
    lv_obj_set_width(ui_settings_screen_switch_sleep_while_serial, 50);
    lv_obj_set_height(ui_settings_screen_switch_sleep_while_serial, 20);
    lv_obj_set_align(ui_settings_screen_switch_sleep_while_serial, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_border_color(ui_settings_screen_switch_sleep_while_serial, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_settings_screen_switch_sleep_while_serial, 255, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_settings_screen_container_option_11 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_11);
    lv_obj_set_width(ui_settings_screen_container_option_11, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_11, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_11,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_sleep_while_usb_text = lv_label_create(ui_settings_screen_container_option_11);
    lv_obj_set_width(ui_settings_screen_label_sleep_while_usb_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_sleep_while_usb_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_sleep_while_usb_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_sleep_while_usb_text, "Sleep with USB");

    ui_settings_screen_switch_sleep_while_usb = lv_switch_create(ui_settings_screen_container_option_11);
    lv_obj_set_width(ui_settings_screen_switch_sleep_while_usb, 50);
    lv_obj_set_height(ui_settings_screen_switch_sleep_while_usb, 20);
    lv_obj_set_align(ui_settings_screen_switch_sleep_while_usb, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_border_color(ui_settings_screen_switch_sleep_while_usb, lv_color_hex(0x000000),
                                  LV_PART_KNOB | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_settings_screen_switch_sleep_while_usb, 255, LV_PART_KNOB | LV_STATE_FOCUSED);

    ui_settings_screen_container_option_10 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_10);
    lv_obj_set_width(ui_settings_screen_container_option_10, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_10, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_10,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_sleep_text = lv_label_create(ui_settings_screen_container_option_10);
    lv_obj_set_width(ui_settings_screen_label_sleep_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_sleep_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_sleep_text, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_sleep_text, "Sleeping in: ");

    ui_settings_screen_button_sleep = lv_button_create(ui_settings_screen_container_option_10);
    lv_obj_set_width(ui_settings_screen_button_sleep, 100);
    lv_obj_set_height(ui_settings_screen_button_sleep, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_button_sleep, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_button_sleep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settings_screen_button_sleep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_sleep_button_text = lv_label_create(ui_settings_screen_button_sleep);
    lv_obj_set_width(ui_settings_screen_label_sleep_button_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_sleep_button_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_sleep_button_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_sleep_button_text, "Sleep");

    ui_settings_screen_container_option_8 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_8);
    lv_obj_set_width(ui_settings_screen_container_option_8, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_8, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_8,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_reboot_text1 = lv_label_create(ui_settings_screen_container_option_8);
    lv_obj_set_width(ui_settings_screen_label_reboot_text1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_reboot_text1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_reboot_text1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_reboot_text1, "Reboot device");

    ui_settings_screen_button_reboot = lv_button_create(ui_settings_screen_container_option_8);
    lv_obj_set_width(ui_settings_screen_button_reboot, 100);
    lv_obj_set_height(ui_settings_screen_button_reboot, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_button_reboot, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_button_reboot, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settings_screen_button_reboot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_reboot_button_text = lv_label_create(ui_settings_screen_button_reboot);
    lv_obj_set_width(ui_settings_screen_label_reboot_button_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_reboot_button_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_reboot_button_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_reboot_button_text, "Reboot");

    ui_settings_screen_container_option_9 = lv_obj_create(ui_settings_screen_panel_panel2);
    lv_obj_remove_style_all(ui_settings_screen_container_option_9);
    lv_obj_set_width(ui_settings_screen_container_option_9, lv_pct(100));
    lv_obj_set_height(ui_settings_screen_container_option_9, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_align(ui_settings_screen_container_option_9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings_screen_container_option_9,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_shipping_mode_test = lv_label_create(ui_settings_screen_container_option_9);
    lv_obj_set_width(ui_settings_screen_label_shipping_mode_test, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_shipping_mode_test, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_shipping_mode_test, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_settings_screen_label_shipping_mode_test, "Shipping mode");

    ui_settings_screen_button_shipping_mode = lv_button_create(ui_settings_screen_container_option_9);
    lv_obj_set_width(ui_settings_screen_button_shipping_mode, 100);
    lv_obj_set_height(ui_settings_screen_button_shipping_mode, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_settings_screen_button_shipping_mode, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settings_screen_button_shipping_mode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_settings_screen_button_shipping_mode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_screen_label_shipping_mode_button_text = lv_label_create(ui_settings_screen_button_shipping_mode);
    lv_obj_set_width(ui_settings_screen_label_shipping_mode_button_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settings_screen_label_shipping_mode_button_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settings_screen_label_shipping_mode_button_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_screen_label_shipping_mode_button_text, "Bye!");

    uic_Screen_Settings_Screen = ui_screen_settings_screen;
    uic_Settings_Screen_Container_Main_Container = ui_settings_screen_container_main_container;
    uic_Settings_Screen_Panel_Panel2 = ui_settings_screen_panel_panel2;
    uic_Settings_Screen_Label_Screen_and_brightness_section = ui_settings_screen_label_screen_and_brightness_section;
    uic_Settings_Screen_Label_Screen_Brightness_text = ui_settings_screen_label_screen_brightness_text;
    uic_Settings_Screen_Dropdown_Brightness = ui_settings_screen_dropdown_brightness;
    uic_Settings_Screen_Label_Scanning_mode_section = ui_settings_screen_label_scanning_mode_section;
    uic_Settings_Screen_Label_BLE_Scanning_text = ui_settings_screen_label_ble_scanning_text;
    uic_Settings_Screen_Switch_BLE_Scanning = ui_settings_screen_switch_ble_scanning;
    uic_Settings_Screen_Label_Wifi_Scanning_text = ui_settings_screen_label_wifi_scanning_text;
    uic_Settings_Screen_Switch_Wifi_scanning = ui_settings_screen_switch_wifi_scanning;
    uic_Settings_Screen_Label_Scan_mode_text = ui_settings_screen_label_scan_mode_text;
    uic_Settings_Screen_Dropdown_performance_mode = ui_settings_screen_dropdown_performance_mode;
    uic_Settings_Screen_Container_Option_1 = ui_settings_screen_container_option_1;
    uic_Settings_Screen_Label_Debug_over_Serial_text = ui_settings_screen_label_debug_over_serial_text;
    uic_Settings_Screen_Switch_Debug_over_Serial = ui_settings_screen_switch_debug_over_serial;
    uic_Settings_Screen_Label_Debug_Level_Text = ui_settings_screen_label_debug_level_text;
    uic_Settings_Screen_Dropdown_Debug_level = ui_settings_screen_dropdown_debug_level;
    uic_Settings_Screen_Label_Sleep_while_serial_text = ui_settings_screen_label_sleep_while_serial_text;
    uic_Settings_Screen_Switch_Sleep_while_Serial = ui_settings_screen_switch_sleep_while_serial;
    uic_Settings_Screen_Switch_Sleep_while_USB = ui_settings_screen_switch_sleep_while_usb;
    uic_Settings_Screen_Button_sleep = ui_settings_screen_button_sleep;
    uic_Settings_Screen_Label_sleep_button_text = ui_settings_screen_label_sleep_button_text;
    uic_Settings_Screen_Button_reboot = ui_settings_screen_button_reboot;
    uic_Settings_Screen_Label_button_text = ui_settings_screen_label_reboot_button_text;
    uic_Settings_Screen_Button_Shipping_mode = ui_settings_screen_button_shipping_mode;

}

void ui_screen_settings_screen_screen_destroy(void)
{
    if(ui_screen_settings_screen) lv_obj_del(ui_screen_settings_screen);

    // NULL screen variables
    uic_Screen_Settings_Screen = NULL;
    ui_screen_settings_screen = NULL;
    uic_Settings_Screen_Container_Main_Container = NULL;
    ui_settings_screen_container_main_container = NULL;
    ui_settings_screen_panel_top_bar2 = NULL;
    ui_settings_screen_top_bar_left_text_top_bar_left_text3 = NULL;
    ui_settings_screen_top_bar_center_text_centertext2 = NULL;
    ui_settings_screen_top_bar_right_text_righttext2 = NULL;
    uic_Settings_Screen_Panel_Panel2 = NULL;
    ui_settings_screen_panel_panel2 = NULL;
    uic_Settings_Screen_Label_Screen_and_brightness_section = NULL;
    ui_settings_screen_label_screen_and_brightness_section = NULL;
    ui_settings_screen_container_option_4 = NULL;
    uic_Settings_Screen_Label_Screen_Brightness_text = NULL;
    ui_settings_screen_label_screen_brightness_text = NULL;
    uic_Settings_Screen_Dropdown_Brightness = NULL;
    ui_settings_screen_dropdown_brightness = NULL;
    uic_Settings_Screen_Label_Scanning_mode_section = NULL;
    ui_settings_screen_label_scanning_mode_section = NULL;
    ui_settings_screen_container_option_5 = NULL;
    uic_Settings_Screen_Label_BLE_Scanning_text = NULL;
    ui_settings_screen_label_ble_scanning_text = NULL;
    uic_Settings_Screen_Switch_BLE_Scanning = NULL;
    ui_settings_screen_switch_ble_scanning = NULL;
    ui_settings_screen_container_option_6 = NULL;
    uic_Settings_Screen_Label_Wifi_Scanning_text = NULL;
    ui_settings_screen_label_wifi_scanning_text = NULL;
    uic_Settings_Screen_Switch_Wifi_scanning = NULL;
    ui_settings_screen_switch_wifi_scanning = NULL;
    ui_settings_screen_container_option_7 = NULL;
    uic_Settings_Screen_Label_Scan_mode_text = NULL;
    ui_settings_screen_label_scan_mode_text = NULL;
    uic_Settings_Screen_Dropdown_performance_mode = NULL;
    ui_settings_screen_dropdown_performance_mode = NULL;
    ui_settings_screen_label_debug_section = NULL;
    uic_Settings_Screen_Container_Option_1 = NULL;
    ui_settings_screen_container_option_1 = NULL;
    uic_Settings_Screen_Label_Debug_over_Serial_text = NULL;
    ui_settings_screen_label_debug_over_serial_text = NULL;
    uic_Settings_Screen_Switch_Debug_over_Serial = NULL;
    ui_settings_screen_switch_debug_over_serial = NULL;
    ui_settings_screen_container_option_2 = NULL;
    uic_Settings_Screen_Label_Debug_Level_Text = NULL;
    ui_settings_screen_label_debug_level_text = NULL;
    uic_Settings_Screen_Dropdown_Debug_level = NULL;
    ui_settings_screen_dropdown_debug_level = NULL;
    ui_settings_screen_container_option_3 = NULL;
    uic_Settings_Screen_Label_Sleep_while_serial_text = NULL;
    ui_settings_screen_label_sleep_while_serial_text = NULL;
    uic_Settings_Screen_Switch_Sleep_while_Serial = NULL;
    ui_settings_screen_switch_sleep_while_serial = NULL;
    ui_settings_screen_container_option_11 = NULL;
    ui_settings_screen_label_sleep_while_usb_text = NULL;
    uic_Settings_Screen_Switch_Sleep_while_USB = NULL;
    ui_settings_screen_switch_sleep_while_usb = NULL;
    ui_settings_screen_container_option_10 = NULL;
    ui_settings_screen_label_sleep_text = NULL;
    uic_Settings_Screen_Button_sleep = NULL;
    ui_settings_screen_button_sleep = NULL;
    uic_Settings_Screen_Label_sleep_button_text = NULL;
    ui_settings_screen_label_sleep_button_text = NULL;
    ui_settings_screen_container_option_8 = NULL;
    ui_settings_screen_label_reboot_text1 = NULL;
    uic_Settings_Screen_Button_reboot = NULL;
    ui_settings_screen_button_reboot = NULL;
    uic_Settings_Screen_Label_button_text = NULL;
    ui_settings_screen_label_reboot_button_text = NULL;
    ui_settings_screen_container_option_9 = NULL;
    ui_settings_screen_label_shipping_mode_test = NULL;
    uic_Settings_Screen_Button_Shipping_mode = NULL;
    ui_settings_screen_button_shipping_mode = NULL;
    ui_settings_screen_label_shipping_mode_button_text = NULL;

}
