// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef UI_SCREEN_MENU_SCREEN_H
#define UI_SCREEN_MENU_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_menu_screen
extern void ui_screen_menu_screen_screen_init(void);
extern void ui_screen_menu_screen_screen_destroy(void);
extern lv_obj_t * ui_screen_menu_screen;
extern lv_obj_t * ui_menu_screen_container_main_container1;
extern lv_obj_t * ui_menu_screen_panel_top_bar1;
extern lv_obj_t * ui_menu_screen_top_bar_left_text_top_bar_left_text2;
extern lv_obj_t * ui_menu_screen_top_bar_center_text_centertext1;
extern lv_obj_t * ui_menu_screen_top_bar_right_text_righttext1;
extern lv_obj_t * ui_menu_screen_container_container5;
extern void ui_event_menu_screen_panel_settings_pannel(lv_event_t * e);
extern lv_obj_t * ui_menu_screen_panel_settings_pannel;
extern lv_obj_t * ui_menu_screen_label_settings_icon;
extern lv_obj_t * ui_menu_screen_label_settings_text;
extern lv_obj_t * ui_menu_screen_label_settings_text_small;
extern lv_obj_t * ui_menu_screen_panel_panel4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_Menu_Screen;
extern lv_obj_t * uic_Menu_Screen_Panel_Alerts_Pannel;
extern lv_obj_t * uic_Menu_Screen_Label_Settings_icon;
extern lv_obj_t * uic_Menu_Screen_Label_Alerts_text_2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

