// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef UI_SCREEN_SPLASH_SCREEN_H
#define UI_SCREEN_SPLASH_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_splash_screen
extern void ui_screen_splash_screen_screen_init(void);
extern void ui_screen_splash_screen_screen_destroy(void);
extern void ui_event_screen_splash_screen(lv_event_t * e);
extern lv_obj_t * ui_screen_splash_screen;
extern lv_obj_t * ui_splash_screen_container_main_container;
extern lv_obj_t * ui_splash_screen_image_dc801_logo;
extern lv_obj_t * ui_splash_screen_label_helgatchi_v2;
extern lv_obj_t * ui_splash_screen_label_hardware_software_versions;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_Splash_Screen;
extern lv_obj_t * uic_Splash_Screen_Container_Main_Container;
extern lv_obj_t * uic_Splash_Screen_Image_Image1;
extern lv_obj_t * uic_Splash_Screen_Label_Helgatchi_V2;
extern lv_obj_t * uic_Splash_Screen_Label_Hardware_Software_Versions;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

