// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

lv_obj_t * uic_Menu_Screen_Label_Alerts_text_2;
lv_obj_t * uic_Menu_Screen_Label_Settings_icon;
lv_obj_t * uic_Menu_Screen_Panel_Alerts_Pannel;
lv_obj_t * uic_Screen_Menu_Screen;
lv_obj_t * ui_screen_menu_screen = NULL;
lv_obj_t * ui_menu_screen_container_main_container1 = NULL;
lv_obj_t * ui_menu_screen_panel_top_bar1 = NULL;
lv_obj_t * ui_menu_screen_top_bar_left_text_top_bar_left_text2 = NULL;
lv_obj_t * ui_menu_screen_top_bar_center_text_centertext1 = NULL;
lv_obj_t * ui_menu_screen_top_bar_right_text_righttext1 = NULL;
lv_obj_t * ui_menu_screen_container_container5 = NULL;
lv_obj_t * ui_menu_screen_panel_settings_pannel = NULL;
lv_obj_t * ui_menu_screen_label_settings_icon = NULL;
lv_obj_t * ui_menu_screen_label_settings_text = NULL;
lv_obj_t * ui_menu_screen_label_settings_text_small = NULL;
lv_obj_t * ui_menu_screen_panel_panel4 = NULL;
// event funtions
void ui_event_menu_screen_panel_settings_pannel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screen_settings_screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_screen_settings_screen_screen_init);
    }
}

// build funtions

void ui_screen_menu_screen_screen_init(void)
{
    ui_screen_menu_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_menu_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menu_screen_container_main_container1 = lv_obj_create(ui_screen_menu_screen);
    lv_obj_remove_style_all(ui_menu_screen_container_main_container1);
    lv_obj_set_width(ui_menu_screen_container_main_container1, lv_pct(95));
    lv_obj_set_height(ui_menu_screen_container_main_container1, lv_pct(95));
    lv_obj_set_align(ui_menu_screen_container_main_container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_screen_container_main_container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menu_screen_container_main_container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_menu_screen_container_main_container1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_menu_screen_container_main_container1, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menu_screen_panel_top_bar1 = lv_obj_create(ui_menu_screen_container_main_container1);
    lv_obj_set_width(ui_menu_screen_panel_top_bar1, lv_pct(100));
    lv_obj_set_height(ui_menu_screen_panel_top_bar1, lv_pct(15));
    lv_obj_set_align(ui_menu_screen_panel_top_bar1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_menu_screen_panel_top_bar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menu_screen_top_bar_left_text_top_bar_left_text2 = ui_label_top_bar_left_text_create(ui_menu_screen_panel_top_bar1);
    lv_obj_set_x(ui_menu_screen_top_bar_left_text_top_bar_left_text2, 0);
    lv_obj_set_y(ui_menu_screen_top_bar_left_text_top_bar_left_text2, 0);
    lv_label_set_text(ui_menu_screen_top_bar_left_text_top_bar_left_text2, "zzz");

    ui_menu_screen_top_bar_center_text_centertext1 = ui_label_top_bar_center_text_create(ui_menu_screen_panel_top_bar1);
    lv_obj_set_x(ui_menu_screen_top_bar_center_text_centertext1, 0);
    lv_obj_set_y(ui_menu_screen_top_bar_center_text_centertext1, 0);
    lv_label_set_text(ui_menu_screen_top_bar_center_text_centertext1, "Menu");

    ui_menu_screen_top_bar_right_text_righttext1 = ui_label_top_bar_right_text_create(ui_menu_screen_panel_top_bar1);
    lv_obj_set_x(ui_menu_screen_top_bar_right_text_righttext1, 0);
    lv_obj_set_y(ui_menu_screen_top_bar_right_text_righttext1, 0);

    ui_menu_screen_container_container5 = lv_obj_create(ui_menu_screen_container_main_container1);
    lv_obj_remove_style_all(ui_menu_screen_container_container5);
    lv_obj_set_width(ui_menu_screen_container_container5, lv_pct(100));
    lv_obj_set_height(ui_menu_screen_container_container5, lv_pct(70));
    lv_obj_set_align(ui_menu_screen_container_container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_screen_container_container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menu_screen_container_container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_menu_screen_container_container5, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_remove_flag(ui_menu_screen_container_container5, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_menu_screen_container_container5, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_snap_x(ui_menu_screen_container_container5, LV_SCROLL_SNAP_CENTER);

    ui_menu_screen_panel_settings_pannel = lv_obj_create(ui_menu_screen_container_container5);
    lv_obj_set_width(ui_menu_screen_panel_settings_pannel, lv_pct(100));
    lv_obj_set_height(ui_menu_screen_panel_settings_pannel, lv_pct(100));
    lv_obj_set_align(ui_menu_screen_panel_settings_pannel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_screen_panel_settings_pannel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menu_screen_panel_settings_pannel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_menu_screen_panel_settings_pannel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_menu_screen_label_settings_icon = lv_label_create(ui_menu_screen_panel_settings_pannel);
    lv_obj_set_width(ui_menu_screen_label_settings_icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menu_screen_label_settings_icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menu_screen_label_settings_icon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menu_screen_label_settings_icon, "&#xf085;");
    lv_obj_set_style_text_font(ui_menu_screen_label_settings_icon, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menu_screen_label_settings_text = lv_label_create(ui_menu_screen_panel_settings_pannel);
    lv_obj_set_width(ui_menu_screen_label_settings_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menu_screen_label_settings_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menu_screen_label_settings_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menu_screen_label_settings_text, "Settings");

    ui_menu_screen_label_settings_text_small = lv_label_create(ui_menu_screen_panel_settings_pannel);
    lv_obj_set_width(ui_menu_screen_label_settings_text_small, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_menu_screen_label_settings_text_small, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_menu_screen_label_settings_text_small, LV_ALIGN_CENTER);
    lv_label_set_text(ui_menu_screen_label_settings_text_small, "Manage device settings");
    lv_obj_set_style_text_font(ui_menu_screen_label_settings_text_small, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menu_screen_panel_panel4 = lv_obj_create(ui_menu_screen_container_container5);
    lv_obj_set_width(ui_menu_screen_panel_panel4, lv_pct(100));
    lv_obj_set_height(ui_menu_screen_panel_panel4, lv_pct(100));
    lv_obj_set_align(ui_menu_screen_panel_panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_screen_panel_panel4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_menu_screen_panel_panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_menu_screen_panel_panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_menu_screen_panel_settings_pannel, ui_event_menu_screen_panel_settings_pannel, LV_EVENT_ALL,
                        NULL);
    uic_Screen_Menu_Screen = ui_screen_menu_screen;
    uic_Menu_Screen_Panel_Alerts_Pannel = ui_menu_screen_panel_settings_pannel;
    uic_Menu_Screen_Label_Settings_icon = ui_menu_screen_label_settings_icon;
    uic_Menu_Screen_Label_Alerts_text_2 = ui_menu_screen_label_settings_text_small;

}

void ui_screen_menu_screen_screen_destroy(void)
{
    if(ui_screen_menu_screen) lv_obj_del(ui_screen_menu_screen);

    // NULL screen variables
    uic_Screen_Menu_Screen = NULL;
    ui_screen_menu_screen = NULL;
    ui_menu_screen_container_main_container1 = NULL;
    ui_menu_screen_panel_top_bar1 = NULL;
    ui_menu_screen_top_bar_left_text_top_bar_left_text2 = NULL;
    ui_menu_screen_top_bar_center_text_centertext1 = NULL;
    ui_menu_screen_top_bar_right_text_righttext1 = NULL;
    ui_menu_screen_container_container5 = NULL;
    uic_Menu_Screen_Panel_Alerts_Pannel = NULL;
    ui_menu_screen_panel_settings_pannel = NULL;
    uic_Menu_Screen_Label_Settings_icon = NULL;
    ui_menu_screen_label_settings_icon = NULL;
    ui_menu_screen_label_settings_text = NULL;
    uic_Menu_Screen_Label_Alerts_text_2 = NULL;
    ui_menu_screen_label_settings_text_small = NULL;
    ui_menu_screen_panel_panel4 = NULL;

}
