// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef UI_SCREEN_STATUS_SCREEN_H
#define UI_SCREEN_STATUS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_status_screen
extern void ui_screen_status_screen_screen_init(void);
extern void ui_screen_status_screen_screen_destroy(void);
extern lv_obj_t * ui_screen_status_screen;
extern lv_obj_t * ui_status_screen_container_main_container;
extern lv_obj_t * ui_status_screen_panel_top_bar;
extern lv_obj_t * ui_status_screen_top_bar_left_text_top_bar_left_text1;
extern lv_obj_t * ui_status_screen_top_bar_center_text_centertext;
extern lv_obj_t * ui_status_screen_top_bar_right_text_righttext;
extern lv_obj_t * ui_status_screen_panel_panel3;
extern lv_obj_t * ui_status_screen_label_label8;
extern lv_obj_t * ui_status_screen_label_label9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_Status_Screen;
extern lv_obj_t * uic_Status_Screen_Container_Main_Container;
extern lv_obj_t * uic_Status_Screen_Panel_Top_Bar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

