// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#ifndef UI_SCREEN_SETTINGS_SCREEN_H
#define UI_SCREEN_SETTINGS_SCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_settings_screen
extern void ui_screen_settings_screen_screen_init(void);
extern void ui_screen_settings_screen_screen_destroy(void);
extern lv_obj_t * ui_screen_settings_screen;
extern lv_obj_t * ui_settings_screen_container_main_container;
extern lv_obj_t * ui_settings_screen_panel_top_bar2;
extern lv_obj_t * ui_settings_screen_top_bar_left_text_top_bar_left_text3;
extern lv_obj_t * ui_settings_screen_top_bar_center_text_centertext2;
extern lv_obj_t * ui_settings_screen_top_bar_right_text_righttext2;
extern lv_obj_t * ui_settings_screen_panel_panel2;
extern lv_obj_t * ui_settings_screen_label_screen_and_brightness_section;
extern lv_obj_t * ui_settings_screen_container_option_4;
extern lv_obj_t * ui_settings_screen_label_screen_brightness_text;
extern lv_obj_t * ui_settings_screen_dropdown_brightness;
extern lv_obj_t * ui_settings_screen_label_scanning_mode_section;
extern lv_obj_t * ui_settings_screen_container_option_5;
extern lv_obj_t * ui_settings_screen_label_ble_scanning_text;
extern lv_obj_t * ui_settings_screen_switch_ble_scanning;
extern lv_obj_t * ui_settings_screen_container_option_6;
extern lv_obj_t * ui_settings_screen_label_wifi_scanning_text;
extern lv_obj_t * ui_settings_screen_switch_wifi_scanning;
extern lv_obj_t * ui_settings_screen_container_option_7;
extern lv_obj_t * ui_settings_screen_label_scan_mode_text;
extern lv_obj_t * ui_settings_screen_dropdown_performance_mode;
extern lv_obj_t * ui_settings_screen_label_debug_section;
extern lv_obj_t * ui_settings_screen_container_option_1;
extern lv_obj_t * ui_settings_screen_label_debug_over_serial_text;
extern lv_obj_t * ui_settings_screen_switch_debug_over_serial;
extern lv_obj_t * ui_settings_screen_container_option_2;
extern lv_obj_t * ui_settings_screen_label_debug_level_text;
extern lv_obj_t * ui_settings_screen_dropdown_debug_level;
extern lv_obj_t * ui_settings_screen_container_option_3;
extern lv_obj_t * ui_settings_screen_label_sleep_while_serial_text;
extern lv_obj_t * ui_settings_screen_switch_sleep_while_serial;
extern lv_obj_t * ui_settings_screen_container_option_11;
extern lv_obj_t * ui_settings_screen_label_sleep_while_usb_text;
extern lv_obj_t * ui_settings_screen_switch_sleep_while_usb;
extern lv_obj_t * ui_settings_screen_container_option_10;
extern lv_obj_t * ui_settings_screen_label_sleep_text;
extern lv_obj_t * ui_settings_screen_button_sleep;
extern lv_obj_t * ui_settings_screen_label_sleep_button_text;
extern lv_obj_t * ui_settings_screen_container_option_8;
extern lv_obj_t * ui_settings_screen_label_reboot_text1;
extern lv_obj_t * ui_settings_screen_button_reboot;
extern lv_obj_t * ui_settings_screen_label_reboot_button_text;
extern lv_obj_t * ui_settings_screen_container_option_9;
extern lv_obj_t * ui_settings_screen_label_shipping_mode_test;
extern lv_obj_t * ui_settings_screen_button_shipping_mode;
extern lv_obj_t * ui_settings_screen_label_shipping_mode_button_text;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen_Settings_Screen;
extern lv_obj_t * uic_Settings_Screen_Container_Main_Container;
extern lv_obj_t * uic_Settings_Screen_Panel_Panel2;
extern lv_obj_t * uic_Settings_Screen_Label_Screen_and_brightness_section;
extern lv_obj_t * uic_Settings_Screen_Label_Screen_Brightness_text;
extern lv_obj_t * uic_Settings_Screen_Dropdown_Brightness;
extern lv_obj_t * uic_Settings_Screen_Label_Scanning_mode_section;
extern lv_obj_t * uic_Settings_Screen_Label_BLE_Scanning_text;
extern lv_obj_t * uic_Settings_Screen_Switch_BLE_Scanning;
extern lv_obj_t * uic_Settings_Screen_Label_Wifi_Scanning_text;
extern lv_obj_t * uic_Settings_Screen_Switch_Wifi_scanning;
extern lv_obj_t * uic_Settings_Screen_Label_Scan_mode_text;
extern lv_obj_t * uic_Settings_Screen_Dropdown_performance_mode;
extern lv_obj_t * uic_Settings_Screen_Container_Option_1;
extern lv_obj_t * uic_Settings_Screen_Label_Debug_over_Serial_text;
extern lv_obj_t * uic_Settings_Screen_Switch_Debug_over_Serial;
extern lv_obj_t * uic_Settings_Screen_Label_Debug_Level_Text;
extern lv_obj_t * uic_Settings_Screen_Dropdown_Debug_level;
extern lv_obj_t * uic_Settings_Screen_Label_Sleep_while_serial_text;
extern lv_obj_t * uic_Settings_Screen_Switch_Sleep_while_Serial;
extern lv_obj_t * uic_Settings_Screen_Switch_Sleep_while_USB;
extern lv_obj_t * uic_Settings_Screen_Button_sleep;
extern lv_obj_t * uic_Settings_Screen_Label_sleep_button_text;
extern lv_obj_t * uic_Settings_Screen_Button_reboot;
extern lv_obj_t * uic_Settings_Screen_Label_button_text;
extern lv_obj_t * uic_Settings_Screen_Button_Shipping_mode;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

