// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Helgatchi-UI

#include "ui.h"

lv_obj_t * uic_Splash_Screen_Label_Hardware_Software_Versions;
lv_obj_t * uic_Splash_Screen_Label_Helgatchi_V2;
lv_obj_t * uic_Splash_Screen_Image_Image1;
lv_obj_t * uic_Splash_Screen_Container_Main_Container;
lv_obj_t * uic_Screen_Splash_Screen;
lv_obj_t * ui_screen_splash_screen = NULL;
lv_obj_t * ui_splash_screen_container_main_container = NULL;
lv_obj_t * ui_splash_screen_image_dc801_logo = NULL;
lv_obj_t * ui_splash_screen_label_helgatchi_v2 = NULL;
lv_obj_t * ui_splash_screen_label_hardware_software_versions = NULL;
// event funtions
void ui_event_screen_splash_screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_screen_menu_screen, LV_SCR_LOAD_ANIM_FADE_OUT, 500, 3000, &ui_screen_menu_screen_screen_init);
    }
}

// build funtions

void ui_screen_splash_screen_screen_init(void)
{
    ui_screen_splash_screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_splash_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_screen_container_main_container = lv_obj_create(ui_screen_splash_screen);
    lv_obj_remove_style_all(ui_splash_screen_container_main_container);
    lv_obj_set_width(ui_splash_screen_container_main_container, lv_pct(95));
    lv_obj_set_height(ui_splash_screen_container_main_container, lv_pct(95));
    lv_obj_set_align(ui_splash_screen_container_main_container, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_splash_screen_container_main_container, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splash_screen_container_main_container, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_splash_screen_container_main_container,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_splash_screen_container_main_container, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_splash_screen_image_dc801_logo = lv_image_create(ui_splash_screen_container_main_container);
    lv_image_set_src(ui_splash_screen_image_dc801_logo, &ui_img_633823932);
    lv_obj_set_width(ui_splash_screen_image_dc801_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_splash_screen_image_dc801_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_splash_screen_image_dc801_logo, lv_pct(0));
    lv_obj_set_y(ui_splash_screen_image_dc801_logo, lv_pct(-10));
    lv_obj_set_align(ui_splash_screen_image_dc801_logo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_splash_screen_image_dc801_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_splash_screen_label_helgatchi_v2 = lv_label_create(ui_splash_screen_container_main_container);
    lv_obj_set_width(ui_splash_screen_label_helgatchi_v2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_splash_screen_label_helgatchi_v2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_splash_screen_label_helgatchi_v2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_splash_screen_label_helgatchi_v2, "Helgatchi V2");

    ui_splash_screen_label_hardware_software_versions = lv_label_create(ui_splash_screen_container_main_container);
    lv_obj_set_width(ui_splash_screen_label_hardware_software_versions, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_splash_screen_label_hardware_software_versions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_splash_screen_label_hardware_software_versions, LV_ALIGN_CENTER);
    lv_label_set_text(ui_splash_screen_label_hardware_software_versions, "HARDWARE: R2.7\nSOFTWARE: V1");
    lv_obj_set_style_text_font(ui_splash_screen_label_hardware_software_versions, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_screen_splash_screen, ui_event_screen_splash_screen, LV_EVENT_ALL, NULL);
    uic_Screen_Splash_Screen = ui_screen_splash_screen;
    uic_Splash_Screen_Container_Main_Container = ui_splash_screen_container_main_container;
    uic_Splash_Screen_Image_Image1 = ui_splash_screen_image_dc801_logo;
    uic_Splash_Screen_Label_Helgatchi_V2 = ui_splash_screen_label_helgatchi_v2;
    uic_Splash_Screen_Label_Hardware_Software_Versions = ui_splash_screen_label_hardware_software_versions;

}

void ui_screen_splash_screen_screen_destroy(void)
{
    if(ui_screen_splash_screen) lv_obj_del(ui_screen_splash_screen);

    // NULL screen variables
    uic_Screen_Splash_Screen = NULL;
    ui_screen_splash_screen = NULL;
    uic_Splash_Screen_Container_Main_Container = NULL;
    ui_splash_screen_container_main_container = NULL;
    uic_Splash_Screen_Image_Image1 = NULL;
    ui_splash_screen_image_dc801_logo = NULL;
    uic_Splash_Screen_Label_Helgatchi_V2 = NULL;
    ui_splash_screen_label_helgatchi_v2 = NULL;
    uic_Splash_Screen_Label_Hardware_Software_Versions = NULL;
    ui_splash_screen_label_hardware_software_versions = NULL;

}
